export const APP_CONTAINER_WIDTH = 1440

export const APP_HEADER_HEIGHT = 64

export const APP_HEADER_LOGO_WIDTH = 147

export const ASIDE_NAVIGATE_WIDTH = 204

export const ASIDE_NAVIGATE_COLLAPSE_WIDTH = 80

export const CANDIDATE_CARD_HEIGHT = 112
