export const MOCK_DND_SCENE_V2 = {
  "new-application": [
    { id: "new-application-1", data: {} },
    { id: "new-application-2", data: {} },
    // { id: "new-application-3", data: {} },
    // { id: "new-application-4", data: {} },
    // { id: "new-application-5", data: {} },
    // { id: "new-application-6", data: {} },
    // { id: "new-application-7", data: {} },
    // { id: "new-application-8", data: {} },
    // { id: "new-application-9", data: {} },
    // { id: "new-application-10", data: {} },
    // { id: "new-application-11", data: {} },
    // { id: "new-application-12", data: {} },
    // { id: "new-application-13", data: {} },
    // { id: "new-application-14", data: {} },
    // { id: "new-application-15", data: {} },
    // { id: "new-application-16", data: {} },
    // { id: "new-application-17", data: {} },
    // { id: "new-application-18", data: {} },
    // { id: "new-application-19", data: {} },
    // { id: "new-application-20", data: {} },
  ],
  screening: [
    { id: "screening-1", data: {} },
    { id: "screening-2", data: {} },
    // { id: "screening-3", data: {} },
    // { id: "screening-4", data: {} },
    // { id: "screening-5", data: {} },
    // { id: "screening-6", data: {} },
    // { id: "screening-7", data: {} },
    // { id: "screening-8", data: {} },
    // { id: "screening-9", data: {} },
    // { id: "screening-10", data: {} },
    // { id: "screening-11", data: {} },
    // { id: "screening-12", data: {} },
    // { id: "screening-13", data: {} },
    // { id: "screening-14", data: {} },
    // { id: "screening-15", data: {} },
    // { id: "screening-16", data: {} },
    // { id: "screening-17", data: {} },
    // { id: "screening-18", data: {} },
    // { id: "screening-19", data: {} },
    // { id: "screening-20", data: {} },
  ],
  interview: [
    { id: "interview-1", data: {} },
    { id: "interview-2", data: {} },
    // { id: "interview-3", data: {} },
    // { id: "interview-4", data: {} },
    // { id: "interview-5", data: {} },
    // { id: "interview-6", data: {} },
    // { id: "interview-7", data: {} },
    // { id: "interview-8", data: {} },
    // { id: "interview-9", data: {} },
    // { id: "interview-10", data: {} },
    // { id: "interview-11", data: {} },
    // { id: "interview-12", data: {} },
    // { id: "interview-13", data: {} },
    // { id: "interview-14", data: {} },
    // { id: "interview-15", data: {} },
    // { id: "interview-16", data: {} },
    // { id: "interview-17", data: {} },
    // { id: "interview-18", data: {} },
    // { id: "interview-19", data: {} },
    // { id: "interview-20", data: {} },
  ],
  offer: [
    { id: "offer-1", data: {} },
    { id: "offer-2", data: {} },
    // { id: "offer-3", data: {} },
    // { id: "offer-4", data: {} },
    // { id: "offer-5", data: {} },
    // { id: "offer-6", data: {} },
    // { id: "offer-7", data: {} },
    // { id: "offer-8", data: {} },
    // { id: "offer-9", data: {} },
    // { id: "offer-10", data: {} },
    // { id: "offer-11", data: {} },
    // { id: "offer-12", data: {} },
    // { id: "offer-13", data: {} },
    // { id: "offer-14", data: {} },
    // { id: "offer-15", data: {} },
    // { id: "offer-16", data: {} },
    // { id: "offer-17", data: {} },
    // { id: "offer-18", data: {} },
    // { id: "offer-19", data: {} },
    // { id: "offer-20", data: {} },
  ],
  hire: [
    { id: "hire-1", data: {} },
    { id: "hire-2", data: {} },
    // { id: "hire-3", data: {} },
    // { id: "hire-4", data: {} },
    // { id: "hire-5", data: {} },
    // { id: "hire-6", data: {} },
    // { id: "hire-7", data: {} },
    // { id: "hire-8", data: {} },
    // { id: "hire-9", data: {} },
    // { id: "hire-10", data: {} },
    // { id: "hire-11", data: {} },
    // { id: "hire-12", data: {} },
    // { id: "hire-13", data: {} },
    // { id: "hire-14", data: {} },
    // { id: "hire-15", data: {} },
    // { id: "hire-16", data: {} },
    // { id: "hire-17", data: {} },
    // { id: "hire-18", data: {} },
    // { id: "hire-19", data: {} },
    // { id: "hire-20", data: {} },
  ],
  failed: [
    { id: "failed-1", data: {} },
    { id: "failed-2", data: {} },
    // { id: "failed-3", data: {} },
    // { id: "failed-4", data: {} },
    // { id: "failed-5", data: {} },
    // { id: "failed-6", data: {} },
    // { id: "failed-7", data: {} },
    // { id: "failed-8", data: {} },
    // { id: "failed-9", data: {} },
    // { id: "failed-10", data: {} },
    // { id: "failed-11", data: {} },
    // { id: "failed-12", data: {} },
    // { id: "failed-13", data: {} },
    // { id: "failed-14", data: {} },
    // { id: "failed-15", data: {} },
    // { id: "failed-16", data: {} },
    // { id: "failed-17", data: {} },
    // { id: "failed-18", data: {} },
    // { id: "failed-19", data: {} },
    // { id: "failed-20", data: {} },
  ],
}
